application: storefrontssar
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /.*
  script: storefrontssar.application
- url: /stylesheets
  static_dir: stylesheets
- url: /css
  static_dir: css
- url: /server
  static_dir: server
- url: /fonts
  static_dir: fonts  
- url: /img
  static_dir: img
- url: /js
  static_dir: js
- url: /(favicon\.ico|robots\.txt)
  static_files: static/\1
  upload: static/(.*)
  expiration: '1d'
- url: /js/images
  static_dir: /js/images

  libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: django
  version: "1.2"








